# Generated by Django 5.0.7 on 2024-07-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cardetails_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardetails',
            options={'verbose_name': 'Car Detail', 'verbose_name_plural': 'Car Details'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
